[server]
headless = true
address = "0.0.0.0"
port = 10000

[browser]
serverAddress = "localhost"
serverPort = 10000


[theme]

primaryColor="#4b0081"
backgroundColor="#000000"
secondaryBackgroundColor="#1e0077"
textColor="#ffffff"
font="monospace"
